name: Deploy Node.js App

on:
  push:
    branches: [main] # Workflow akan berjalan setiap ada perubahan pada branch 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'deploy'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: node-deploy

    steps:
      # Checkout kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install # atau 'yarn install'

      # Jalankan build (jika diperlukan)
      - name: Build app
        run: npm run build || echo "No build step required"

      # List files setelah install dan build (opsional)
      - name: List files
        run: ls -la

      # Deploy aplikasi ke server menggunakan SSH dan rsync

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1